import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {NuqsAdapter} from 'nuqs/adapters/next/app';
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import {outfit, poppins, roboto, openSans, montserrat} from "./fonts";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${poppins.variable} ${roboto.variable} ${openSans.variable} ${montserrat.variable}`}>
      <body
        className={inter.className}
      >
       <NuqsAdapter>
        <ConvexClientProvider> 
        {children}
        <Toaster/>
        </ConvexClientProvider>
       </NuqsAdapter>
      </body>
    </html>
  );
}
